import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

import Link from "next/link"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>
          Front End Developer | Designer | Kristina Simon | Kristina Chausheva
        </title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          href="nextjs-test/public/images/favicon.png"
        />
      </Head>
      <div className="logo">KC</div>
      <nav className="nav">
        <div className="logo">KC</div>
        <li>
          <Link href="/about">
            <a>About</a>
          </Link>
        </li>
        <li>
          <Link href="/skills">
            <a>My Skills</a>
          </Link>
        </li>
        <li>
          <Link href="/work">
            <a>Work</a>
          </Link>
        </li>
        <li>
          <Link href="/contact">
            <a>Contact</a>
          </Link>
        </li>
        <li>
          <Link href="/blog">
            <a>Blog Post</a>
          </Link>
        </li>
      </nav>
      <main className={styles.main}>
        <div className="box">
          <h1 className="greeting">Hi, I am Kristina Simon</h1>
          <h2 className="loader">
            <span className="m">W</span>
            <span className="m">E</span>
            <span className="m">B</span>
            <span className="m">&nbsp;</span>
            <span className="m">D</span>
            <span className="m">E</span>
            <span className="m">V</span>
            <span className="m">E</span>
            <span className="m">L</span>
            <span className="m">O</span>
            <span className="m">P</span>
            <span className="m">E</span>
            <span className="m">R</span>
          </h2>
          <a href="#">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Contact me
          </a>
        </div>
        <div className="scroll">scroll down &rarr;</div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
