import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="box">
          <h1 className="greeting">Hi, I am Kristina Simon</h1>
          <h2 className="loader">
            <span className="m">W</span>
            <span className="m">E</span>
            <span className="m">B</span>
            <span className="m">&nbsp;</span>
            <span className="m">D</span>
            <span className="m">E</span>
            <span className="m">V</span>
            <span className="m">E</span>
            <span className="m">L</span>
            <span className="m">O</span>
            <span className="m">P</span>
            <span className="m">E</span>
            <span className="m">R</span>
          </h2>
          <a href="#">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Contact me
          </a>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
